# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # Menggunakan "go run main.go" sebagai perintah
  cmd = "go build -o ./tmp/main main.go"
  bin = "./tmp/main"
  # Binari yang dihasilkan
  # full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  
  # Jeda sebelum me-rebuild aplikasi (dalam milidetik)
  delay = 1000
  
  # Direktori yang akan dilewati/tidak dipantau
  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
  
  # Ekstensi file yang akan dipantau untuk perubahan
  include_ext = ["go", "tpl", "tmpl", "html"]
  
  # File yang akan dilewati berdasarkan ekspresi reguler
  exclude_regex = ["_test\\.go"]

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  # Tampilkan log waktu
  time = true

[screen]
  clear_on_rebuild = true