root = "."
tmp_dir = "tmp"

[build]
  pre_cmd = ["cmd /c if not exist tmp mkdir tmp"]
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ./main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  full_bin = ""
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
